[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
game = "HCMBs4McFkMXzrCi9xbgSejtok3q8qD2WHZbbHwGxWLy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
